using Catalog.Common.Extensions;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi.Any;
using Microsoft.OpenApi.Models;
using System.Reflection;
using System.Xml.Linq;

namespace Catalog.API.Helpers;

public class OpenApiSchemaTransformer : IOpenApiSchemaTransformer
{
    public Task TransformAsync(OpenApiSchema schema, OpenApiSchemaTransformerContext context, CancellationToken cancellationToken)
    {
        var type = context.JsonTypeInfo.Type;
        if (type.IsEnum)
        {
            schema.Format = Enum.GetUnderlyingType(type).Name.ToCamelCase();

            schema.Enum = [.. Enum.GetValues(type)
                                  .Cast<object>()
                                  .Select(enumValue => new OpenApiInteger(Convert.ToInt32(enumValue)))
                                  .Cast<IOpenApiAny>()];

            var enumDescriptions = new OpenApiObject();
            foreach (var enumValue in Enum.GetValues(type))
            {
                enumDescriptions.Add(Convert.ToInt32(enumValue).ToString(), new OpenApiString($"{enumValue}"));
            }

            schema.Extensions["x-enumDescriptions"] = enumDescriptions;
        }

        if ((type.IsClass || type.IsEnum))
        {
            TransformProblemDetailsSchema(schema, type);

            if (type.Namespace != null && type.Namespace.Contains("Catalog."))
            {
                schema.Description = GetXmlDocumentation(type, "summary");
                AddPropertyDescriptions(schema, type);
            }
        }

        return Task.CompletedTask;
    }

    private static void TransformProblemDetailsSchema(OpenApiSchema schema, Type type)
    {
        if (type.FullName == "Microsoft.AspNetCore.Mvc.ProblemDetails")
        {
            schema.Description = "A machine-readable format for specifying errors in HTTP API responses based on https://tools.ietf.org/html/rfc7807.";

            if (schema.Properties != null)
            {
                if (schema.Properties.TryGetValue("type", out var typeProperty))
                {
                    typeProperty.Description = "A URI reference [RFC3986] that identifies the problem type. This specification\r\n  encourages that, when dereferenced, it provide human-readable documentation for\r\n the problem type (e.g., using HTML [W3C.REC-html5-20141028]). When this member\r\n  is not present, its value is assumed to be \"about:blank\".";
                }

                if (schema.Properties.TryGetValue("title", out var titleProperty))
                {
                    titleProperty.Description = "A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence\r\n of the problem, except for purposes of localization(e.g., using proactive content negotiation;\r\n  see[RFC7231], Section 3.4).";
                }

                if (schema.Properties.TryGetValue("status", out var statusProperty))
                {
                    statusProperty.Description = "The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.";
                }

                if (schema.Properties.TryGetValue("detail", out var detailProperty))
                {
                    detailProperty.Description = "A human-readable explanation specific to this occurrence of the problem.";
                }

                if (schema.Properties.TryGetValue("instance", out var instanceProperty))
                {
                    instanceProperty.Description = "A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.";
                }
            }
        }
    }

    private static string? GetXmlDocumentation(MemberInfo member, string tagName)
    {
        string memberName;

        if (member is Type type)
        {
            memberName = $"T:{type.FullName}";
        }
        else if (member is PropertyInfo property)
        {
            memberName = $"P:{property.DeclaringType?.FullName}.{property.Name}";
        }
        else
        {
            return null; // Unsupported member type
        }

        var xmlComments = LoadXmlComments(member.DeclaringType ?? (Type)member);
        var memberElement = xmlComments.Descendants("member").FirstOrDefault(m => m.Attribute("name")?.Value == memberName);
        return memberElement?.Element(tagName)?.Value.Trim();
    }

    private static void AddPropertyDescriptions(OpenApiSchema schema, Type type)
    {
        foreach (var property in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            if (IsSystemProperty(property))
            {
                continue;
            }

            schema.Properties ??= new Dictionary<string, OpenApiSchema>();

            var description = GetXmlDocumentation(property, "summary");
            var camelCaseName = property.Name.LowercaseFirstChar();

            if (schema.Properties.TryGetValue(camelCaseName, out OpenApiSchema? value))
            {
                value.Description = description;
            }
            else
            {
                schema.Properties[camelCaseName] = new OpenApiSchema
                {
                    Description = description,
                };
            }
        }
    }

    private static bool IsSystemProperty(PropertyInfo property)
    {
        // List of unwanted system-level properties
        var unwantedProperties = new[]
        {
            "Length", "LongLength", "Rank", "SyncRoot", "IsReadOnly", "IsFixedSize", "IsSynchronized"
        };

        return unwantedProperties.Contains(property.Name);
    }

    private static XDocument LoadXmlComments(Type type)
    {
        var assemblyDirectory = Path.GetDirectoryName(type.Assembly.Location);

        if (assemblyDirectory == null)
        {
            return new XDocument();
        }

        var xmlFileName = $"{type.Assembly.GetName().Name}.xml";
        var xmlPath = Path.Combine(assemblyDirectory, xmlFileName);

        if (File.Exists(xmlPath))
        {
            return XDocument.Load(xmlPath);
        }

        return new XDocument();
    }
}
