using System.Text;
using System;

namespace Generator.Shared.Extensions;

internal static class StringBuilderExtensions
{
    internal static StringBuilder GenerateHeader(this StringBuilder stringBuilder)
    {
        stringBuilder.AppendLine("#nullable disable");
        stringBuilder.AppendLine("// <auto-generated>");
        stringBuilder.AppendLine($"// Latest Generated Date : {DateTime.Now}");
        stringBuilder.AppendLine(string.Empty);
        return stringBuilder;
    }

    internal static StringBuilder GenerateNameSpace(this StringBuilder stringBuilder, string @namespace)
    {
        stringBuilder.AppendLine($"namespace {@namespace};");
        stringBuilder.AppendLine(string.Empty);
        return stringBuilder;
    }
}