// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Catalog.Domain.Models;
using Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Catalog.Infrastructure.Persistence.Configurations
{
    public partial class CustomFieldConfiguration : IEntityTypeConfiguration<CustomField>
    {
        public void Configure(EntityTypeBuilder<CustomField> entity)
        {
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.CustomFieldGroup).WithMany(p => p.CustomFields)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomField_CustomFieldGroup");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent).HasConstraintName("FK_CustomField_CustomField");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CustomField> entity);
    }
}
