// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Catalog.Domain.Models;
using Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Catalog.Infrastructure.Persistence.Configurations
{
    public partial class ProductCategoryConfiguration : IEntityTypeConfiguration<ProductCategory>
    {
        public void Configure(EntityTypeBuilder<ProductCategory> entity)
        {
            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasConstraintName("FK_ProductCategory_Parent");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductCategory> entity);
    }
}
