// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Catalog.Domain.Models;
using Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Catalog.Infrastructure.Persistence.Configurations
{
    public partial class ProductCategoryCustomFieldGroupConfiguration : IEntityTypeConfiguration<ProductCategoryCustomFieldGroup>
    {
        public void Configure(EntityTypeBuilder<ProductCategoryCustomFieldGroup> entity)
        {
            entity.HasOne(d => d.CustomFieldGroup).WithMany(p => p.ProductCategoryCustomFieldGroups)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductCategoryCustomFieldGroup_CustomFieldGroup");

            entity.HasOne(d => d.ProductCategory).WithMany(p => p.ProductCategoryCustomFieldGroups)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductCategoryCustomFieldGroup_ProductCategory");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductCategoryCustomFieldGroup> entity);
    }
}
