// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Catalog.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace Catalog.Infrastructure.Persistence.Configurations;

public partial class ProductConfiguration : IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<Product> entity)
    {
        entity.ToTable("Product");

        entity.Property(e => e.BarCode)
            .HasMaxLength(32)
            .IsUnicode(false);
        entity.Property(e => e.CreatedAt).HasColumnType("datetime");
        entity.Property(e => e.DateStamp).HasColumnType("datetime");
        entity.Property(e => e.ExpiryDate).HasColumnType("datetime");
        entity.Property(e => e.GlobalDeliveryCountries).HasMaxLength(256);
        entity.Property(e => e.Identifier)
            .HasMaxLength(128)
            .IsUnicode(false);
        entity.Property(e => e.Image).IsUnicode(false);
        entity.Property(e => e.ModifiedAt).HasColumnType("datetime");
        entity.Property(e => e.Name).HasMaxLength(128);
        entity.Property(e => e.Sku)
            .HasMaxLength(32)
            .IsUnicode(false)
            .HasColumnName("SKU");
        entity.Property(e => e.Tags).HasMaxLength(256);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Product> entity);
}
